INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL, ACCOUNTNONEXPIRED, ACCOUNTNONLOCKED, CREDENTIALSNONEXPIRED, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin@admin.com', 1, 1, 1, 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL, ACCOUNTNONEXPIRED, ACCOUNTNONLOCKED, CREDENTIALSNONEXPIRED, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$10$n20UGeoQeWTfX0wP0NEGs.l/2PONagLmJvJTJCQMm80iihhCCF83a', 'enabled@user.com', 1, 1, 1, 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL, ACCOUNTNONEXPIRED, ACCOUNTNONLOCKED, CREDENTIALSNONEXPIRED, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$10$ALsevDME8ecpaqQRqWTiYurfXR36QeGIZuKBbPkCJ.dM/L0y2qUp.', 'disabled@user.com', 0, 1, 1, 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO ROLE (ID, ROLE) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE (ID, ROLE) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USERS_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USERS_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USERS_ROLE (USER_ID, ROLE_ID) VALUES (3, 1);
